'use server'

import { createClient } from '@/lib/supabase/server'
import type { Group } from '@/types'

type CreateGroupResult =
  | { ok: true; group: Group }
  | { ok: false; message: string }

type CloseGroupResult =
  | { ok: true }
  | { ok: false; message: string }

/**
 * Get all active groups
 * @returns Array of active groups
 */
export async function getActiveGroups(): Promise<Group[]> {
  try {
    const supabase = await createClient()

    const { data, error } = await supabase
      .from('groups')
      .select('*')
      .eq('status', 'active')
      .order('created_at', { ascending: false })

    if (error) {
      console.error('Error fetching active groups:', error)
      return []
    }

    return data || []
  } catch (error) {
    console.error('Error getting active groups:', error)
    return []
  }
}

/**
 * Create a new group
 * @param name - The group name
 * @param sellerId - The seller ID (optional)
 * @returns The created group or error message
 */
export async function createGroup(
  name: string,
  sellerId?: string
): Promise<CreateGroupResult> {
  try {
    if (!name || name.trim().length === 0) {
      return { ok: false, message: 'Group name is required' }
    }

    const supabase = await createClient()

    const insertData: {
      name: string
      client_code: string
      status: 'active'
      created_by?: string
    } = {
      name: name.trim(),
      client_code: '', // Will be auto-generated by trigger
      status: 'active',
    }

    if (sellerId) {
      insertData.created_by = sellerId
    }

    const { data, error } = await supabase
      .from('groups')
      .insert(insertData)
      .select()
      .single()

    if (error) {
      console.error('Error creating group:', error)
      return { ok: false, message: 'Failed to create group' }
    }

    return { ok: true, group: data }
  } catch (error) {
    console.error('Error creating group:', error)
    return { ok: false, message: 'An unexpected error occurred' }
  }
}

/**
 * Get a group by client code
 * @param code - The 6-digit client code
 * @returns Group data or null if not found
 */
export async function getGroupByCode(code: string): Promise<Group | null> {
  try {
    if (!code || code.trim().length === 0) {
      return null
    }

    const supabase = await createClient()

    const { data, error } = await supabase
      .from('groups')
      .select('*')
      .eq('client_code', code.trim())
      .single()

    if (error) {
      console.error('Error fetching group by code:', error)
      return null
    }

    return data
  } catch (error) {
    console.error('Error getting group by code:', error)
    return null
  }
}

/**
 * Close a group
 * @param groupId - The group ID
 * @returns Success or error message
 */
export async function closeGroup(groupId: string): Promise<CloseGroupResult> {
  try {
    if (!groupId) {
      return { ok: false, message: 'Group ID is required' }
    }

    const supabase = await createClient()

    const { error } = await supabase
      .from('groups')
      .update({ status: 'closed' })
      .eq('id', groupId)

    if (error) {
      console.error('Error closing group:', error)
      return { ok: false, message: 'Failed to close group' }
    }

    return { ok: true }
  } catch (error) {
    console.error('Error closing group:', error)
    return { ok: false, message: 'An unexpected error occurred' }
  }
}
